// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AtomTester
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// HelloWorld - Use 'HelloWorldParams' to pass parameters into this method.
        /// </summary>
        public void HelloWorld()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UIUntitledAtomWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient;
            WinControl uIUntitledAtomDocument = this.UIUntitledAtomWindow.UIChromeLegacyWindowWindow.UIUntitledAtomDocument;
            WinControl uIChromeLegacyWindowDocument = this.UIUntitledAtomWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(173, 98));

            // Type 'h' in 'untitled — Atom' document
            Keyboard.SendKeys(uIUntitledAtomDocument, this.HelloWorldParams.UIUntitledAtomDocumentSendKeys, ModifierKeys.None);

            // Type 'ello world' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.HelloWorldParams.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// HelloWorld2 - Use 'HelloWorld2Params' to pass parameters into this method.
        /// </summary>
        public void HelloWorld2()
        {
            #region Variable Declarations
            WinControl uIUntitledAtomDocument = this.UIUntitledAtomWindow.UIChromeLegacyWindowWindow.UIUntitledAtomDocument;
            #endregion

            // Click 'untitled — Atom' document
            Mouse.Click(uIUntitledAtomDocument, new Point(351, 318));

            // Type 'hello world' in 'untitled — Atom' document
            Keyboard.SendKeys(uIUntitledAtomDocument, this.HelloWorld2Params.UIUntitledAtomDocumentSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// TypeInSearch - Use 'TypeInSearchParams' to pass parameters into this method.
        /// </summary>
        public void TypeInSearch()
        {
            #region Variable Declarations
            WinControl uIUntitledAtomDocument = this.UIUntitledAtomWindow.UIChromeLegacyWindowWindow.UIUntitledAtomDocument;
            #endregion

            // Click 'untitled — Atom' document
            Mouse.Click(uIUntitledAtomDocument, new Point(186, 160));

            // Type 'Control + t' in 'untitled — Atom' document
            Keyboard.SendKeys(uIUntitledAtomDocument, this.TypeInSearchParams.UIUntitledAtomDocumentSendKeys, ModifierKeys.Control);

           // Type 'settings{Enter}' in 'untitled — Atom' document
            Keyboard.SendKeys(uIUntitledAtomDocument, this.TypeInSearchParams.UIUntitledAtomDocumentSendKeys1, ModifierKeys.None);
        }
        
        /// <summary>
        /// ChangeSettings
        /// </summary>
        public void ChangeSettings()
        {
            #region Variable Declarations
            WinControl uIUntitledAtomDocument = this.UIUntitledAtomWindow.UIChromeLegacyWindowWindow.UIUntitledAtomDocument;
            WinText uIFileText = this.UIUntitledAtomWindow.UIFileMenuButton.UIFileText;
            WinMenuItem uISettingsCtrlCommaMenuItem = this.UIItemWindow.UIItemMenuBar.UIItemClient.UISettingsCtrlCommaMenuItem;
            #endregion

            // Click 'untitled — Atom' document
            Mouse.Click(uIUntitledAtomDocument, new Point(261, 303));

            // Click 'File' label
            Mouse.Click(uIFileText, new Point(9, 10));

            // Click 'Settings Ctrl+Comma' menu item
            Mouse.Click(uISettingsCtrlCommaMenuItem, new Point(38, 16));

            // Click 'untitled — Atom' document
            Mouse.Click(uIUntitledAtomDocument, new Point(445, 291));
        }
        
        #region Properties
        public virtual HelloWorldParams HelloWorldParams
        {
            get
            {
                if ((this.mHelloWorldParams == null))
                {
                    this.mHelloWorldParams = new HelloWorldParams();
                }
                return this.mHelloWorldParams;
            }
        }
        
        public virtual HelloWorld2Params HelloWorld2Params
        {
            get
            {
                if ((this.mHelloWorld2Params == null))
                {
                    this.mHelloWorld2Params = new HelloWorld2Params();
                }
                return this.mHelloWorld2Params;
            }
        }
        
        public virtual TypeInSearchParams TypeInSearchParams
        {
            get
            {
                if ((this.mTypeInSearchParams == null))
                {
                    this.mTypeInSearchParams = new TypeInSearchParams();
                }
                return this.mTypeInSearchParams;
            }
        }
        
        public UIUntitledAtomWindow UIUntitledAtomWindow
        {
            get
            {
                if ((this.mUIUntitledAtomWindow == null))
                {
                    this.mUIUntitledAtomWindow = new UIUntitledAtomWindow();
                }
                return this.mUIUntitledAtomWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private HelloWorldParams mHelloWorldParams;
        
        private HelloWorld2Params mHelloWorld2Params;
        
        private TypeInSearchParams mTypeInSearchParams;
        
        private UIUntitledAtomWindow mUIUntitledAtomWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'HelloWorld'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class HelloWorldParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'h' in 'untitled — Atom' document
        /// </summary>
        public string UIUntitledAtomDocumentSendKeys = "h";
        
        /// <summary>
        /// Type 'ello world' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "ello world";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'HelloWorld2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class HelloWorld2Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'hello world' in 'untitled — Atom' document
        /// </summary>
        public string UIUntitledAtomDocumentSendKeys = "hello world";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TypeInSearch'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class TypeInSearchParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Control + t' in 'untitled — Atom' document
        /// </summary>
        public string UIUntitledAtomDocumentSendKeys = "t";
        
        /// <summary>
        /// Type 'settings{Enter}' in 'untitled — Atom' document
        /// </summary>
        public string UIUntitledAtomDocumentSendKeys1 = "settings{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUntitledAtomWindow : WinWindow
    {
        
        public UIUntitledAtomWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "untitled — Atom";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("untitled — Atom");
            this.WindowTitles.Add("Settings — atom://config — Atom");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIFileMenuButton UIFileMenuButton
        {
            get
            {
                if ((this.mUIFileMenuButton == null))
                {
                    this.mUIFileMenuButton = new UIFileMenuButton(this);
                }
                return this.mUIFileMenuButton;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIFileMenuButton mUIFileMenuButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "137096624";
            this.WindowTitles.Add("untitled — Atom");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("untitled — Atom");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        
        public WinControl UIUntitledAtomDocument
        {
            get
            {
                if ((this.mUIUntitledAtomDocument == null))
                {
                    this.mUIUntitledAtomDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIUntitledAtomDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIUntitledAtomDocument.WindowTitles.Add("untitled — Atom");
                    #endregion
                }
                return this.mUIUntitledAtomDocument;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("untitled — Atom");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        
        private WinControl mUIUntitledAtomDocument;
        
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFileMenuButton : WinControl
    {
        
        public UIFileMenuButton(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "File";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "MenuButton";
            this.WindowTitles.Add("untitled — Atom");
            #endregion
        }
        
        #region Properties
        public WinText UIFileText
        {
            get
            {
                if ((this.mUIFileText == null))
                {
                    this.mUIFileText = new WinText(this);
                    #region Search Criteria
                    this.mUIFileText.SearchProperties[WinText.PropertyNames.Name] = "File";
                    this.mUIFileText.WindowTitles.Add("untitled — Atom");
                    #endregion
                }
                return this.mUIFileText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIFileText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_2";
            #endregion
        }
        
        #region Properties
        public UIItemMenuBar UIItemMenuBar
        {
            get
            {
                if ((this.mUIItemMenuBar == null))
                {
                    this.mUIItemMenuBar = new UIItemMenuBar(this);
                }
                return this.mUIItemMenuBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemMenuBar mUIItemMenuBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemMenuBar : WinMenuBar
    {
        
        public UIItemMenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinMenuItem UISettingsCtrlCommaMenuItem
        {
            get
            {
                if ((this.mUISettingsCtrlCommaMenuItem == null))
                {
                    this.mUISettingsCtrlCommaMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUISettingsCtrlCommaMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Settings Ctrl+Comma";
                    #endregion
                }
                return this.mUISettingsCtrlCommaMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUISettingsCtrlCommaMenuItem;
        #endregion
    }
}
